repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.6.0
  hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - push
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
    - id: black
      language_version: python3.11
